#!/usr/bin/env zsh


echo "Installing antibody plugins"
antibody bundle < ~/.config/zsh/lib/plugins_list.txt > ~/.config/zsh/lib/plugins.zsh

echo "Setting up git"
git config --global user.name "thearticulate-edboard"
git config --global user.email "articulate58@gmail.com"
git config --global init.defaultBranch main
git config --global pull.rebase true
git config --global --add safe.directory /storage/emulated/0/Documents/testing
echo "git setup finished"

chsh -s zsh
