#!/usr/bin/env zsh

PS3="Enter a number: "
select user in Astha Akanksha R
do
    if [[ $user == "Akanksha" ]]                                                                                                                    
	then
		user="Mini"
	else 
		
	fi
	sleep 1 && break
done

echo "USER=${user} :)" >> ~/env-vars

clear
echo ""
printf "%40s\n" "Hello \033[1;34m${user}\033[0m :), setup will begin in a moment"
echo "Hello \033[1;34m${user}\033[0m :)" > /data/data/com.termux/files/usr/etc/motd
~/scripts/spinner.sh sleep 5

echo "Installing antibody plugins"
echo ""
antibody bundle < ~/.config/zsh/lib/plugins_list.txt > ~/.config/zsh/lib/plugins.zsh

echo "Setting up git"
echo ""
echo ""
git config --global user.name "thearticulate-edboard"
git config --global user.email "articulate58@gmail.com"
git config --global init.defaultBranch main
git config --global pull.rebase true
git config --global --add safe.directory /storage/emulated/0/Documents/testing
echo "git setup finished"
echo ""
echo ""
chsh -s zsh


